---
title: "p8105_hw5_tl3195"
author: "Tingyi Li"
date: "2023-11-14"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

#Problem 2
Import data and iterate over file names and read in data
```{r,show_col_types = FALSE}
hw5_data=
  tibble(list.files("./data"))|>
  mutate(files=paste(list.files("./data")))

read_data=function(x) {
  data=read_csv(paste0("./data/", x))|>
    mutate(files_names=x)
}

arm = map_df(hw5_data$files, read_data)

arm
```

Tidy the result
```{r}
arm_data=
  arm|>
  janitor::clean_names()|>
  gather(value = arm_value, key = week, week_1:week_8)|>
  mutate(
    week=as.integer(str_remove(week, "week_")),
    subject_id=as.integer(str_extract(files_names, "[0-9][0-9]")),
    file_names = ifelse(str_detect(files_names, "con"), "Control", "Experiment"),
  )|>
  mutate(across(.cols = c(files_names, week, subject_id), as.factor)) |>
  select(file_names, subject_id, week, arm_value)

arm_data
```



